name: build-and-test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make build
      - name: Run tests
        run: |
          make test
